version: "3"
services:
  gradle:
    image: opendigitaleducation/gradle:4.5.1
    working_dir: /home/gradle/project
    volumes:
      - $PWD:$PWD
      - ./:/home/gradle/project
      - ~/.m2:/home/gradle/.m2
      - ~/.gradle:/home/gradle/.gradle
  node:
    image: opendigitaleducation/node:10
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.npmrc:/home/node/.npmrc
      - ~/.bowerrc:/home/node/.bowerrc
      - ~/.gradle:/home/node/.gradle
