GRANT USAGE ON SCHEMA diary TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA diary TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA diary TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA diary TO "apps";